# Generated by Django 3.2.12 on 2022-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Уникальное название '),
        ),
    ]
