# Generated by Django 3.2.12 on 2022-09-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_link', '0003_alter_links_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=999999, verbose_name='Ссылка'),
        ),
    ]
